### ISSUE TITLE
Destroy perfect-scrollbar

### ISSUE THREAD

**Issue by OxLeon** [svbatalov/angular-perfect-scrollbar-2#2]
Hi there! how could I destroy perfect-scrollbar ? 
I tried to use jquery $("#feed").perfectScrollbar('destroy') , but not work.

Some idea?

**Comment by svbatalov** [comment]
Hi. If you really need to destroy scrollbar manually, you may try something like `PerfectScrollbar.destroy(document.querySelector('.scroll-wrapper'))`.

**Comment by svbatalov** [comment]
I just fixed a typo in the cleanup code, possibly related to your issue: cbde3a0b

**Comment by OxLeon** [comment]
I'm going to try it, I need to destroy it because i can't drag elements in html5, if i remove perfect scrollbar i can drag.
 For this reason I need to destroy it.

**Comment by svbatalov** [comment]
OK, let me know how it goes. The hack above seem to work with the provided example app. Also in the latest version you can use `ng-if` to render scrollbars conditionally -- `PS.destroy(el)` should be called automatically when scope dies.
